 set serveroutput ON
DECLARE
  PD_CHANGEDATETIME DATE;
  PS_CHANGEDBY VARCHAR2(200);
  PS_AREA VARCHAR2(200);
  PS_CHANGEDFILED_ELEMENT VARCHAR2(200);
  PS_OLDVALUE VARCHAR2(200);
  PS_NEWVALUE VARCHAR2(200);
BEGIN
  PD_CHANGEDATETIME := sysdate;
  PS_CHANGEDBY := null;
  PS_AREA := null;
  PS_CHANGEDFILED_ELEMENT := 'CFE';
  PS_OLDVALUE := NULL;
  PS_NEWVALUE := null;

  CERTIFICATION_CRUD.AUDITLOG_INSERT(
    PD_CHANGEDATETIME => PD_CHANGEDATETIME,
    PS_CHANGEDBY => PS_CHANGEDBY,
    PS_AREA => PS_AREA,
    PS_CHANGEDFILED_ELEMENT => PS_CHANGEDFILED_ELEMENT,
    PS_OLDVALUE => PS_OLDVALUE,
    PS_NEWVALUE => PS_NEWVALUE
  );
END;
