'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''DupCorrectCertificationUC class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class DupCorrectCertificationUC

    '''<summary>
    '''pnlDupCorrectCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDupCorrectCertification As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccessText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMatlNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMatlNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpeedRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpeedRating As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMatlNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatlNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSpeedRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpeedRating As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnView As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvDuplicateCertificates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDuplicateCertificates As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CancelAlertPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelAlertPopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hidCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlCancelAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCancelAlert As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Button_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_OK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_Cancel As Global.System.Web.UI.WebControls.Button
End Class
