'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''GSOCertificationUC class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class GSOCertificationUC

    '''<summary>
    '''pnlGSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGSO As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlGSOCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGSOCertificate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPopupTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPopupTarget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnDefaultValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnDefaultValues As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblInfoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfoText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCertificationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCertificationNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCertificationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCertificationNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ppvCertificationNUmber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvCertificationNUmber As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatchNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBatchNumMassUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBatchNumMassUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCertDateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCertDateSubmitted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCertDateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCertDateSubmitted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalExtCertdateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalExtCertdateSubmitted As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ppvCertDateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvCertDateSubmitted As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblCertDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCertDateApproved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCertDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCertDateApproved As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calextCertDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calextCertDateApproved As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ppvCertDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvCertDateApproved As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblRenewalRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRenewalRequired As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optlstRenewalRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optlstRenewalRequired As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ppvRenewalRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvRenewalRequired As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblActiveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''optlstActiveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optlstActiveStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ppvActiveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvActiveStatus As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblMaterialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterialNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMaterialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaterialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ppvMaterialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvMaterialNo As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblProductData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDiscDateTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiscDateTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDiscDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiscDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDateAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateAssigned As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDateAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateAssigned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalExtdateAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalExtdateAssigned As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ppvDateAssigned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvDateAssigned As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblDateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateSubmitted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateSubmitted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalExtdateSubmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalExtdateSubmitted As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ppvDateSubmited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvDateSubmited As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''lblDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateApproved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateApproved As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calextDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calextDateApproved As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ppvDateApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppvDateApproved As Global.Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator

    '''<summary>
    '''btnGettestResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGettestResult As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBlankResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBlankResult As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SimilarTirePopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SimilarTirePopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlSimilarTireFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSimilarTireFound As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSimilarTireMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimilarTireMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSimilarCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSimilarCertificate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSimilarSKUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimilarSKUID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSimilarMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSimilarMaterial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BatchNumMassUpdatePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BatchNumMassUpdatePopup As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlBatchNumMassUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBatchNumMassUpdate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBatchNumMassUpdateMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatchNumMassUpdateMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTempBatchNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTempBatchNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTempBatchNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempBatchNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGSOBatchNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSOBatchNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGSOBatchNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSOBatchNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ChangedFieldsPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangedFieldsPopup As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlChangedFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlChangedFields As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvChangedFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvChangedFields As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSaveReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveReasons As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelReasons As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucTestResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucTestResults As Global.CooperTire.ICS.Web.TestResultsUC
End Class
