DECLARE
  PS_SKU VARCHAR2(200);
  PI_CERTIFICATIONID NUMBER;
  PS_CERTIFICATIONNUMBER VARCHAR2(200);
  PD_DATEASSIGNED DATE;
  PD_DATESUBMITED DATE;
  PD_DATEAPPROVED DATE;
  PS_ACTIVESTATUS VARCHAR2(200);
  PS_RENEWALREQUIRED CHAR(1);
  PI_NOM_COUNTRYOFMANUFACTURE NUMBER;
  PS_NOM_CUSTOMER VARCHAR2(200);
  PS_NOM_IMPORTER VARCHAR2(200);
  PS_NOM_IMPORTERADDRESS VARCHAR2(200);
  PS_NOM_IMPORTERREPRESENTATIVE VARCHAR2(200);
  PS_NOM_COUNTRYLOCATION VARCHAR2(200);
BEGIN
   PS_SKU := 'W11-3456-32453';
  PI_CERTIFICATIONID := 4;
  PS_CERTIFICATIONNUMBER := 'PS_CERTIFICATIONNUMBER';
  PD_DATEASSIGNED := sysdate;
  PD_DATESUBMITED := sysdate;
  PD_DATEAPPROVED := sysdate;
  PS_ACTIVESTATUS := 'PS_ACTIVESTATUS';
  PS_RENEWALREQUIRED := 'y';
  PI_NOM_COUNTRYOFMANUFACTURE := 1;
  PS_NOM_CUSTOMER := 'PS_NOM_CUSTOMER';
  PS_NOM_IMPORTER := 'PS_NOM_IMPORTER';
  PS_NOM_IMPORTERADDRESS := 'PS_NOM_IMPORTERADDRESS';
  PS_NOM_IMPORTERREPRESENTATIVE := 'PS_NOM_IMPORTERREPRESENTATIVE';
  PS_NOM_COUNTRYLOCATION := 'PS_NOM_COUNTRYLOCATION';

  CERTIFICATION_CRUD.CERTIFICATES_NOM_INSERT(
    PS_SKU => PS_SKU,
    PI_CERTIFICATIONID => PI_CERTIFICATIONID,
    PS_CERTIFICATIONNUMBER => PS_CERTIFICATIONNUMBER,
    PD_DATEASSIGNED => PD_DATEASSIGNED,
    PD_DATESUBMITED => PD_DATESUBMITED,
    PD_DATEAPPROVED => PD_DATEAPPROVED,
    PS_ACTIVESTATUS => PS_ACTIVESTATUS,
    PS_RENEWALREQUIRED => PS_RENEWALREQUIRED,
    PI_NOM_COUNTRYOFMANUFACTURE => PI_NOM_COUNTRYOFMANUFACTURE,
    PS_NOM_CUSTOMER => PS_NOM_CUSTOMER,
    PS_NOM_IMPORTER => PS_NOM_IMPORTER,
    PS_NOM_IMPORTERADDRESS => PS_NOM_IMPORTERADDRESS,
    PS_NOM_IMPORTERREPRESENTATIVE => PS_NOM_IMPORTERREPRESENTATIVE,
    PS_NOM_COUNTRYLOCATION => PS_NOM_COUNTRYLOCATION
  );
END;
