  DROP TABLE "APP_MESSAGE" cascade constraints purge;
  DROP TABLE "BEADUNSEATDTL" cascade constraints purge;
  DROP TABLE "BEADUNSEATHDR" cascade constraints purge;
  DROP TABLE "BRAND" cascade constraints purge;
  DROP TABLE "BRANDREGION" cascade constraints purge;
  DROP TABLE "CERTIFICATE" cascade constraints purge;
  DROP TABLE "CERTIFICATEDEFAULTVALUE" cascade constraints purge;
  DROP TABLE "CERTIFICATETYPEDEFAULTVALUE" cascade constraints purge;
  DROP TABLE "CERTIFICATIONSEARCHTYPE" cascade constraints purge;
  DROP TABLE "CERTIFICATIONTYPE" cascade constraints purge;
  DROP TABLE "CERTIFICATION_AUDIT_LOG" cascade constraints purge;
  DROP TABLE "COUNTRY" cascade constraints purge;
  DROP TABLE "DEFAULTFIELD" cascade constraints purge;
  DROP TABLE "ENDURANCEDTL" cascade constraints purge;
  DROP TABLE "ENDURANCEHDR" cascade constraints purge;
  DROP TABLE "HIGHSPEEDDTL" cascade constraints purge;
  DROP TABLE "HIGHSPEEDHDR" cascade constraints purge;
  DROP TABLE "MEASUREDTL" cascade constraints purge;
  DROP TABLE "MEASUREHDR" cascade constraints purge;
  DROP TABLE "NPR_MASTER" cascade constraints purge;
  DROP TABLE "PLUNGERDTL" cascade constraints purge;
  DROP TABLE "PLUNGERHDR" cascade constraints purge;
  DROP TABLE "PRODUCT" cascade constraints purge;
  DROP TABLE "PRODUCTCERTIFICATE" cascade constraints purge;
  DROP TABLE "PRODUCTCOUNTRY" cascade constraints purge;
  DROP TABLE "REGION" cascade constraints purge;
  DROP TABLE "SEARCHTYPE" cascade constraints purge;
  DROP TABLE "SKUMAIN" cascade constraints purge;
  DROP TABLE "SOUNDDETAIL" cascade constraints purge;
  DROP TABLE "SOUNDHDR" cascade constraints purge;
  DROP TABLE "SPEEDTESTDETAIL" cascade constraints purge;
  DROP TABLE "TIRETYPE" cascade constraints purge;
  DROP TABLE "TREADWEARDTL" cascade constraints purge;
  DROP TABLE "TREADWEARHDR" cascade constraints purge;
  DROP TABLE "WETGRIPDETAIL" cascade constraints purge;
  DROP TABLE "WETGRIPHDR" cascade constraints purge;  
  drop table "EXCEPTIONREPORT" cascade constraints PURGE;
  drop table "CUSTOMER" cascade constraints PURGE;
  
  DROP SEQUENCE "APP_MESSAGE_SEQ";
  DROP SEQUENCE "BEADUNSEATID_SEQ";
  DROP SEQUENCE "CERTIFICATIONID_SEQ";
  DROP SEQUENCE "CHANGELOGID_SEQ";
  DROP SEQUENCE "COUNTRYID_SEQ";
  DROP SEQUENCE "ENDURANCEID_SEQ";
  DROP SEQUENCE "HIGHSPEEDID_SEQ";
  DROP SEQUENCE "MEASUREID_SEQ";
  DROP SEQUENCE "NPRID_SEQ";
  DROP SEQUENCE "PLUNGERID_SEQ";
  DROP SEQUENCE "REGIONID_SEQ";
  DROP SEQUENCE "SEARCHTYPEID_SEQ";
  DROP SEQUENCE "SKUID_SEQ";
  DROP SEQUENCE "SOUNDID_SEQ";
  DROP SEQUENCE "TREADWEARID_SEQ";
  DROP SEQUENCE "WETGRIPID_SEQ";
  DROP SEQUENCE "CERTIFICATEID_SEQ";
   Commit;
