'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''SessionTimeOutMonitorUC class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class SessionTimeOutMonitorUC

    '''<summary>
    '''TimerTimeOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimerTimeOut As Global.System.Web.UI.Timer

    '''<summary>
    '''hidTimeOutFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTimeOutFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ConfirmPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlTimeout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTimeout As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSessionExpireInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSessionExpireInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNaviHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNaviHome As Global.System.Web.UI.WebControls.Button
End Class
