DECLARE
  PI_SKUID NUMBER;
  PS_SKU VARCHAR2(200);
  PS_CERTIFICATIONTYPENAME VARCHAR2(200);
  PS_CERTIFICATENUMBER VARCHAR2(200);
  PD_DATESUBMITED DATE;
  PC_ACTIVESTATUS VARCHAR2(200);
  PD_DATEASSIGNED_EGI DATE;
  PD_DATEAPPROVED_CEGI DATE;
  PC_RENEWALREQUIRED_CGIN VARCHAR2(200);
  PC_SUPPLEMENTALREQUIRED_EI VARCHAR2(200);
  PS_SUPPLEMENTALNUMBER_EI VARCHAR2(200);
  PS_JOBREPORTNUMBER_CEN VARCHAR2(200);
  PS_EXTENSION_EN VARCHAR2(200);
  PS_SUPPLEMENTALMOLDSTAMPING_E VARCHAR2(200);
  PS_EMARKREFERENCE_I VARCHAR2(200);
  PD_EXPIRYDATE_I DATE;
  PS_FAMILY_I VARCHAR2(200);
  PS_PRODUCTLOCATION_C VARCHAR2(200);
  PS_COUNTRYOFMANUFACTURE_N VARCHAR2(200);
  PS_CUSTOMER_N VARCHAR2(200);
  PS_CUSTOMERSPECIFIC_N VARCHAR2(200);
  PS_IMPORTER_N VARCHAR2(200);
  PS_IMPORTERADDRESS_N VARCHAR2(200);
  PS_IMPORTERREPRESENTATIVE_N VARCHAR2(200);
  PS_COUNTRYLOCATION_N VARCHAR2(200);
  PS_BATCHNUMBER_G VARCHAR2(200);
BEGIN
  PI_SKUID := 7;
  PS_SKU := '36S-205-1279';
  PS_CERTIFICATIONTYPENAME := 'Imark';
  PS_CERTIFICATENUMBER := 'Icert007';
  PD_DATESUBMITED := NULL;
  PC_ACTIVESTATUS := 'y';
  PD_DATEASSIGNED_EGI := sysdate;
  PD_DATEAPPROVED_CEGI := NULL;
  PC_RENEWALREQUIRED_CGIN := NULL;
  PC_SUPPLEMENTALREQUIRED_EI := NULL;
  PS_SUPPLEMENTALNUMBER_EI := '171';
  PS_JOBREPORTNUMBER_CEN := NULL;
  PS_EXTENSION_EN := 'ext 558';
  PS_SUPPLEMENTALMOLDSTAMPING_E := NULL;
  PS_EMARKREFERENCE_I := NULL;
  PD_EXPIRYDATE_I := NULL;
  PS_FAMILY_I := 'fam';
  PS_PRODUCTLOCATION_C := NULL;
  PS_COUNTRYOFMANUFACTURE_N := NULL;
  PS_CUSTOMER_N := NULL;
  PS_CUSTOMERSPECIFIC_N := NULL;
  PS_IMPORTER_N := NULL;
  PS_IMPORTERADDRESS_N := NULL;
  PS_IMPORTERREPRESENTATIVE_N := NULL;
  PS_COUNTRYLOCATION_N := NULL;
  PS_BATCHNUMBER_G := NULL;

  CERTIFICATION_CRUD.CERTIFICATE_SAVE(
    PI_SKUID => PI_SKUID,
    PS_SKU => PS_SKU,
    PS_CERTIFICATIONTYPENAME => PS_CERTIFICATIONTYPENAME,
    PS_CERTIFICATENUMBER => PS_CERTIFICATENUMBER,
    PD_DATESUBMITED => PD_DATESUBMITED,
    PC_ACTIVESTATUS => PC_ACTIVESTATUS,
    PD_DATEASSIGNED_EGI => PD_DATEASSIGNED_EGI,
    PD_DATEAPPROVED_CEGI => PD_DATEAPPROVED_CEGI,
    PC_RENEWALREQUIRED_CGIN => PC_RENEWALREQUIRED_CGIN,
    PC_SUPPLEMENTALREQUIRED_EI => PC_SUPPLEMENTALREQUIRED_EI,
    PS_SUPPLEMENTALNUMBER_EI => PS_SUPPLEMENTALNUMBER_EI,
    PS_JOBREPORTNUMBER_CEN => PS_JOBREPORTNUMBER_CEN,
    PS_EXTENSION_EN => PS_EXTENSION_EN,
    PS_SUPPLEMENTALMOLDSTAMPING_E => PS_SUPPLEMENTALMOLDSTAMPING_E,
    PS_EMARKREFERENCE_I => PS_EMARKREFERENCE_I,
    PD_EXPIRYDATE_I => PD_EXPIRYDATE_I,
    PS_FAMILY_I => PS_FAMILY_I,
    PS_PRODUCTLOCATION_C => PS_PRODUCTLOCATION_C,
    PS_COUNTRYOFMANUFACTURE_N => PS_COUNTRYOFMANUFACTURE_N,
    PS_CUSTOMER_N => PS_CUSTOMER_N,
    PS_CUSTOMERSPECIFIC_N => PS_CUSTOMERSPECIFIC_N,
    PS_IMPORTER_N => PS_IMPORTER_N,
    PS_IMPORTERADDRESS_N => PS_IMPORTERADDRESS_N,
    PS_IMPORTERREPRESENTATIVE_N => PS_IMPORTERREPRESENTATIVE_N,
    PS_COUNTRYLOCATION_N => PS_COUNTRYLOCATION_N,
    PS_BATCHNUMBER_G => PS_BATCHNUMBER_G
  );
END;