DECLARE
  AS_MACHINEID VARCHAR2(20);
  AD_DATERECORDED DATE;
  AS_PROCESSNAME VARCHAR2(30);
  AX_RECORDDATA VARCHAR2(4000);
  AS_MESSAGECODE VARCHAR2(10);
  AS_MESSAGE VARCHAR2(4000);
BEGIN
  AS_MACHINEID := NULL;
  AD_DATERECORDED := sysdate;
  AS_PROCESSNAME := 'AS_PROCESSNAME';
  AX_RECORDDATA := 'AX_RECORDDATA';
  AS_MESSAGECODE := '100100';
  AS_MESSAGE := 'Test';

  APP_MESSAGE_OPERATIONS.APP_MESSAGE_INSERT(
    AS_MACHINEID => null,
    AD_DATERECORDED => sysdate,
    AS_PROCESSNAME => 'AS_PROCESSNAME',
    AX_RECORDDATA => 'AX_RECORDDATA',
    AS_MESSAGECODE => '100100',
    AS_MESSAGE => 'Test'
  );
END;
select * from app_message