DECLARE
  PS_SKU VARCHAR2(200);
  PI_CERTIFICATIONID NUMBER;
  PS_CERTIFICATIONNUMBER VARCHAR2(200);
  PD_DATEASSIGNED DATE;
  PD_DATESUBMITED DATE;
  PD_DATEAPPROVED DATE;
  PS_ACTIVESTATUS VARCHAR2(200);
  PS_RENEWALREQUIRED CHAR(1);
  PS_GSO_BATCHNUMBER VARCHAR2(200);
BEGIN
   PS_SKU := 'W11-3456-32453';
  PI_CERTIFICATIONID := 2;
  PS_CERTIFICATIONNUMBER := 'PS_CERTIFICATIONNUMBER';
  PD_DATEASSIGNED := sysdate;
  PD_DATESUBMITED := sysdate;
  PD_DATEAPPROVED := sysdate;
  PS_ACTIVESTATUS := 'PS_ACTIVESTATUS';
  PS_RENEWALREQUIRED := 'y';
  PS_GSO_BATCHNUMBER := 'PS_GSO_BATCHNUMBER';

  CERTIFICATION_CRUD.CERTIFICATES_GSO_INSERT(
    PS_SKU => PS_SKU,
    PI_CERTIFICATIONID => PI_CERTIFICATIONID,
    PS_CERTIFICATIONNUMBER => PS_CERTIFICATIONNUMBER,
    PD_DATEASSIGNED => PD_DATEASSIGNED,
    PD_DATESUBMITED => PD_DATESUBMITED,
    PD_DATEAPPROVED => PD_DATEAPPROVED,
    PS_ACTIVESTATUS => PS_ACTIVESTATUS,
    PS_RENEWALREQUIRED => PS_RENEWALREQUIRED,
    PS_GSO_BATCHNUMBER => PS_GSO_BATCHNUMBER
  );
END;
