'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''RenameCertificationUC class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class RenameCertificationUC

    '''<summary>
    '''pnlRenameCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRenameCertification As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccessText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccessText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOldCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldCertNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOldExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldExtension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewCertNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewExtension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOldCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldCertNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOldExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldExtension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FTBOldExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FTBOldExtension As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''txtNewCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewCertNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNewExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewExtension As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FTBNewExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FTBNewExtension As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblErrOldCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrOldCertNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrOldExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrOldExtension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrNewCertNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrNewCertNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrNewExtension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrNewExtension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ConfirmPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hidConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblWarningMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarningMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSaveConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelAlertPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelAlertPopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hidCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlCancelAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCancelAlert As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Button_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_OK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button_Cancel As Global.System.Web.UI.WebControls.Button
End Class
